@startuml
:用户删除操作;
if(是否为今天的日志) then(是)
    :根据今天删除;
else(否)
    :根据不是今天操作删除;
endif
@enduml
@startuml
:根据今天删除;
:打卡天数-1;
:打卡状态变为未打卡;
:成员签到日期中去除(最后一个);
:连续签到天数判断;
if(判断是否是连续7天签到) then(是)
    :圈子活跃度-7;
else(否)
    :圈子活跃度-1;
endif;
@enduml
@startuml
:根据不是今天操作删除;
:打卡天数-1;
:不改变打卡状态;
:成员签到日期中去除;
:连续签到天数判断;
if(判断是否连续7天签到) then(是)
    :圈子活跃度-7;
else(否)
    :圈子活跃度-1;
@enduml
@startuml
:连续打卡天数判断;
:得到连续打卡的记录(去重);
:截断连续打卡记录;
if(删除的日期是连续打卡中的数据) then(是)
    :连续打卡数据改变;
else(否)
    :连续打卡数据不改变;
endif;
if(删除的连续打卡天数是否为最后一天) then(是)
    :连续打卡天数-1;
else(否)
    :连续打卡天数正常判断;
@enduml
@startuml
:用户发表日志;
:设置日志创建时间;
:根据userid和circleid查询出来用户加入圈子的信息;
:设置用户最后打卡时间;
:设置用户打卡状态(1);
:用户打卡天数+1;
:用户连续打卡+1;
:保存设置用户签到日期到列表中;
if(用户是否为连续签到7天) then(是)
    :用户活跃度+5;
else(否)
    :用户活跃度+1;
endif
@enduml
@startuml
:用户进入圈子;
if(是否是圈子成员) then(是)
    :直接查询全部圈子日志数据;
else(否)
    :过滤仅仅圈子内可见日志数据;
@enduml
@startuml
start;
:用户删除日志;
if(用户删除是否为今日日志) then(是)
    :用户打卡状态设置为0;
endif;
:设置打卡天数;
:设置连续打卡天数;
:设置用户所在圈子活跃度信息;
:删除用户打卡列表中的日志信息;
end;
@enduml
@startuml
:删除日志;
:设置日志状态为删除状态;
if(判断日记是否为今天) then(是)
    if(判断是否删除日记后今天全部日记删除) then(是)
        :打卡状态设置为未打卡(0);
        :用户打卡天数-1;
        :删除打卡日历中的打卡日历;
    else(否)
        :打卡状态设置为主题部分打卡(1);
@enduml